### ISSUE TITLE
Not able to use carbon icons

### ISSUE THREAD

**Issue by skakrecha** [codeat3/blade-carbon-icons#52]
Using Blade icons and installed other icons set without any issue.
But not able to use carbon icons

Unable to locate a class or view for component [carbon-sigma-32]. (View: /Users/friday/Sites/mystud/resources/views/layouts/_menus.blade.php)

**Comment by swapnilsarwe** [comment]
Sorry for the inconvenience, post major upgrade (1.* to 2.*) to package due to change in file name, README missed an update. 
You can use the icons by skipping the `-32` from the name. Also kindly update the package in you composer.json to `^2.0` for the latest changes.
